server:
  port: 8080

spring:
  application:
    name: captcha-service

logging:
  level:
    root: INFO

captcha:
  TTL: 120s
  chars-count: 5
  secret-key: "ajsdhjashjdASDAsdamnksdnajsndjQEWQwdkmiasdcsnjdnfsdFSdfksndjfnjnsdjf"
